# Simple workflow for deploying static content to GitHub Pages (PRODUCTION)
name: Deploy production to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required permissions for branch-based deployment
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages-production"
  cancel-in-progress: false

jobs:
  # Single deploy job for production
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate file listing
        run: |
          chmod +x file_giver/generate_listing.sh
          ./file_giver/generate_listing.sh
      
      - name: Copy content to main directory
        run: |
          chmod +x .github/scripts/copy-dirs.sh
          ./.github/scripts/copy-dirs.sh
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: main
          branch: gh-pages
          clean-exclude: pr-preview/
          force: false
